# Generated by Django 5.0.4 on 2024-04-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_address_teacher_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name_plural": "1. Teacher"},
        ),
    ]
