# Generated by Django 5.0.4 on 2024-04-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_teacher_detail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="qualification",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="mobile_no",
        ),
    ]
